version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install --save-dev webpack webpack-cli
      - npm install
  build:
    commands:
      - echo Building project...
      - npm run build
      - npm run deploy
artifacts:
  files:
    - '*'

  