version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install --save-dev webpack webpack-cli
  build:
    commands:
      - echo Building project...
      - webpack-cli
      - sam deploy

  