version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "osf-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1f27i2ysqggrm"
s3_prefix = "osf-sam"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
